In [1]:
import pandas as pd

In [13]:
df_energia= pd.read_csv("consumo_energia_iot - consumo_energia_iot.csv",index_col=0)
df_energia

,Municipio,Estrato,Consumo_kWh,Voltaje_Promedio,Horas_Pico_kWh,Tipo_Medidor,Estado_Pago
ID_Medidor,,,,,,,
MED-5001,Villamaría,Estrato 3,130.5,118.0,32.74,Monofásico Digital,Al Día
MED-5002,Palestina,Estrato 2,175.0,120.5,19.97,Bifásico Inteligente,Al Día
MED-5003,Palestina,Estrato 1,220.0,118.0,11.71,Bifásico Inteligente,Mora
MED-5004,Neira,Estrato 4,130.5,128.0,64.26,Monofásico Digital,Al Día
MED-5005,Neira,Estrato 3,175.0,120.5,14.13,Monofásico Digital,Mora
...,...,...,...,...,...,...,...
MED-5088,Villamaría,Estrato 2,220.0,118.0,34.78,Trifásico Industrial,Al Día
MED-5089,Manizales,Estrato 3,220.0,122.0,62.85,Monofásico Digital,Al Día
MED-5090,Villamaría,Estrato 2,290.5,120.5,39.57,Bifásico Inteligente,Al Día
MED-5091,Palestina,Estrato 3,290.5,122.0,14.73,Trifásico Industrial,Al Día
MED-5092,Neira,Estrato 3,220.0,120.5,22.41,Trifásico Industrial,Financiado

In [ ]:
#Punto 1.1: Extrae de forma aislada la columna Consumo_kWh como un objeto pd.Series
consumo=df_energia["Consumo_kWh"]
consumo,type(consumo)

(0       130.5
 1       175.0
 2       220.0
 3       130.5
 4       175.0
         ...
 1007    220.0
 1008    220.0
 1009    290.5
 1010    290.5
 1011    220.0
 Name: Consumo_kWh, Length: 1012, dtype: float64,
 pandas.Series)

In [7]:
#Punto 1.2 : y crea una nueva vista con las columnas Municipio, Estrato y Voltaje_Promedio.
nueva_vista=df_energia[["Municipio","Estrato","Voltaje_Promedio"]]
nueva_vista

       Municipio    Estrato  Voltaje_Promedio
0     Villamaría  Estrato 3             118.0
1      Palestina  Estrato 2             120.5
2      Palestina  Estrato 1             118.0
3          Neira  Estrato 4             128.0
4          Neira  Estrato 3             120.5
...          ...        ...               ...
1007  Villamaría  Estrato 2             118.0
1008   Manizales  Estrato 3             122.0
1009  Villamaría  Estrato 2             120.5
1010   Palestina  Estrato 3             122.0
1011       Neira  Estrato 3             120.5

[1012 rows x 3 columns]

In [8]:
#Punto 2:Mediante el indexador .loc[], extrae todos los datos de la fila ubicada en el índice 150.

row150=df_energia.loc[[150]]
row150

,ID_Medidor,Municipio,Estrato,Consumo_kWh,Voltaje_Promedio,Horas_Pico_kWh,Tipo_Medidor,Estado_Pago
150,MED-5151,Neira,Estrato 2,130.5,112.5,31.42,Trifásico Industrial,Financiado

In [ ]:
#Punto 3:  Detecta y remueve las filas redundantes con .drop_duplicates() para garantizar que cada registro sea único en la tabla.

df_energia.drop_duplicates()

,ID_Medidor,Municipio,Estrato,Consumo_kWh,Voltaje_Promedio,Horas_Pico_kWh,Tipo_Medidor,Estado_Pago
0,MED-5001,Villamaría,Estrato 3,130.5,118.0,32.74,Monofásico Digital,Al Día
1,MED-5002,Palestina,Estrato 2,175.0,120.5,19.97,Bifásico Inteligente,Al Día
2,MED-5003,Palestina,Estrato 1,220.0,118.0,11.71,Bifásico Inteligente,Mora
3,MED-5004,Neira,Estrato 4,130.5,128.0,64.26,Monofásico Digital,Al Día
4,MED-5005,Neira,Estrato 3,175.0,120.5,14.13,Monofásico Digital,Mora
...,...,...,...,...,...,...,...,...
995,MED-5996,Villamaría,Estrato 2,175.0,120.5,15.18,Monofásico Digital,Al Día
996,MED-5997,Villamaría,Estrato 2,175.0,125.5,13.07,Trifásico Industrial,Al Día
997,MED-5998,Palestina,Estrato 1,130.5,125.5,42.16,Monofásico Digital,Al Día
998,MED-5999,Neira,Estrato 3,175.0,120.5,60.44,Trifásico Industrial,Al Día
999,MED-6000,Palestina,Comercial,NaN,120.5,23.32,Monofásico Digital,Al Día

In [10]:
#Punto4: Filtra los registros para identificar predios con un consumo elevado, seleccionando aquellos con Consumo_kWh > 250.0.
PrediosConConsumoAlto=df_energia[df_energia["Consumo_kWh"]>250.0]
PrediosConConsumoAlto

,ID_Medidor,Municipio,Estrato,Consumo_kWh,Voltaje_Promedio,Horas_Pico_kWh,Tipo_Medidor,Estado_Pago
13,MED-5014,Neira,Estrato 4,290.5,112.5,69.74,Bifásico Inteligente,Al Día
16,MED-5017,Palestina,Estrato 1,290.5,118.0,12.81,Trifásico Industrial,Al Día
29,MED-5030,Manizales,Estrato 1,360.0,122.0,74.21,Monofásico Digital,Financiado
30,MED-5031,Neira,Estrato 2,290.5,125.5,6.57,Bifásico Inteligente,Financiado
40,MED-5041,Manizales,Estrato 2,290.5,122.0,66.32,Trifásico Industrial,Al Día
...,...,...,...,...,...,...,...,...
987,MED-5988,Palestina,Estrato 3,480.0,120.5,71.90,Bifásico Inteligente,Al Día
988,MED-5989,Palestina,Estrato 4,360.0,112.5,10.73,Monofásico Digital,Mora
1002,MED-5083,Palestina,Comercial,290.5,120.5,19.83,Monofásico Digital,Al Día
1009,MED-5090,Villamaría,Estrato 2,290.5,120.5,39.57,Bifásico Inteligente,Al Día
1010,MED-5091,Palestina,Estrato 3,290.5,122.0,14.73,Trifásico Industrial,Al Día

In [12]:
#Punto 5: Utiliza .isin() para recuperar únicamente los medidores instalados en los municipios de Chinchiná y Villamaría.
filtro = df_energia[
    df_energia["Municipio"].isin(["Chinchiná", "Villamaría"])
]
filtro

,ID_Medidor,Municipio,Estrato,Consumo_kWh,Voltaje_Promedio,Horas_Pico_kWh,Tipo_Medidor,Estado_Pago
0,MED-5001,Villamaría,Estrato 3,130.5,118.0,32.74,Monofásico Digital,Al Día
5,MED-5006,Chinchiná,Estrato 4,175.0,120.5,50.49,Bifásico Inteligente,Financiado
8,MED-5009,Villamaría,Estrato 2,130.5,122.0,45.63,Bifásico Inteligente,Mora
14,MED-5015,Chinchiná,Estrato 3,130.5,118.0,5.48,Bifásico Inteligente,Al Día
15,MED-5016,Chinchiná,Estrato 3,95.0,118.0,49.84,Monofásico Digital,Al Día
...,...,...,...,...,...,...,...,...
995,MED-5996,Villamaría,Estrato 2,175.0,120.5,15.18,Monofásico Digital,Al Día
996,MED-5997,Villamaría,Estrato 2,175.0,125.5,13.07,Trifásico Industrial,Al Día
1006,MED-5087,Villamaría,Comercial,130.5,122.0,21.92,Monofásico Digital,Al Día
1007,MED-5088,Villamaría,Estrato 2,220.0,118.0,34.78,Trifásico Industrial,Al Día
1009,MED-5090,Villamaría,Estrato 2,290.5,120.5,39.57,Bifásico Inteligente,Al Día

In [ ]:
#Punto 6:Utilizando el método .between(), extrae todos los registros cuyo Voltaje_Promedio se mantenga en el rango óptimo de 118.0 a 122.0 voltios inclusive.
VoltajePromedio=df_energia[df_energia["Voltaje_Promedio"].between(118.0,122.0)]
VoltajePromedio

,Municipio,Estrato,Consumo_kWh,Voltaje_Promedio,Horas_Pico_kWh,Tipo_Medidor,Estado_Pago
ID_Medidor,,,,,,,
MED-5001,Villamaría,Estrato 3,130.5,118.0,32.74,Monofásico Digital,Al Día
MED-5002,Palestina,Estrato 2,175.0,120.5,19.97,Bifásico Inteligente,Al Día
MED-5003,Palestina,Estrato 1,220.0,118.0,11.71,Bifásico Inteligente,Mora
MED-5005,Neira,Estrato 3,175.0,120.5,14.13,Monofásico Digital,Mora
MED-5006,Chinchiná,Estrato 4,175.0,120.5,50.49,Bifásico Inteligente,Financiado
...,...,...,...,...,...,...,...
MED-5088,Villamaría,Estrato 2,220.0,118.0,34.78,Trifásico Industrial,Al Día
MED-5089,Manizales,Estrato 3,220.0,122.0,62.85,Monofásico Digital,Al Día
MED-5090,Villamaría,Estrato 2,290.5,120.5,39.57,Bifásico Inteligente,Al Día
MED-5091,Palestina,Estrato 3,290.5,122.0,14.73,Trifásico Industrial,Al Día
MED-5092,Neira,Estrato 3,220.0,120.5,22.41,Trifásico Industrial,Financiado

In [ ]:

#Punto 7:Aplica una consulta con .query() para filtrar aquellos inmuebles donde Estrato == 'Comercial' y el Estado_Pago == 'Mora'.
queryEnergia= df_energia.query("Estrato=='Comercial' & Estado_Pago == 'Mora'")

queryEnergia

,Municipio,Estrato,Consumo_kWh,Voltaje_Promedio,Horas_Pico_kWh,Tipo_Medidor,Estado_Pago
ID_Medidor,,,,,,,
MED-5059,Villamaría,Comercial,290.5,122.0,75.92,Trifásico Industrial,Mora
MED-5085,Manizales,Comercial,220.0,118.0,38.27,Monofásico Digital,Mora
MED-5096,Chinchiná,Comercial,130.5,128.0,47.36,Monofásico Digital,Mora
MED-5116,Villamaría,Comercial,175.0,120.5,74.32,Monofásico Digital,Mora
MED-5130,Chinchiná,Comercial,95.0,120.5,44.48,Monofásico Digital,Mora
MED-5155,Villamaría,Comercial,NaN,120.5,82.10,Monofásico Digital,Mora
MED-5204,Palestina,Comercial,220.0,120.5,24.62,Bifásico Inteligente,Mora
MED-5239,Villamaría,Comercial,95.0,120.5,37.48,Monofásico Digital,Mora
MED-5254,Neira,Comercial,220.0,122.0,60.39,Monofásico Digital,Mora
MED-5282,Chinchiná,Comercial,290.5,128.0,75.34,Monofásico Digital,Mora
MED-5291,Palestina,Comercial,220.0,112.5,73.90,Bifásico Inteligente,Mora
MED-5329,Manizales,Comercial,NaN,120.5,44.94,Monofásico Digital,Mora
MED-5349,Manizales,Comercial,95.0,118.0,50.55,Monofásico Digital,Mora
MED-5468,Manizales,Comercial,175.0,120.5,8.51,Monofásico Digital,Mora
MED-5470,Villamaría,Comercial,290.5,118.0,58.66,Bifásico Inteligente,Mora
MED-5501,Chinchiná,Comercial,130.5,125.5,28.92,Monofásico Digital,Mora
MED-5502,Manizales,Comercial,220.0,118.0,56.56,Monofásico Digital,Mora
MED-5504,Villamaría,Comercial,220.0,122.0,65.62,Monofásico Digital,Mora
MED-5508,Chinchiná,Comercial,220.0,NaN,33.44,Monofásico Digital,Mora
MED-5528,Palestina,Comercial,360.0,125.5,52.83,Monofásico Digital,Mora
MED-5644,Chinchiná,Comercial,220.0,118.0,35.88,Monofásico Digital,Mora
MED-5668,Palestina,Comercial,95.0,118.0,72.71,Monofásico Digital,Mora
MED-5708,Palestina,Comercial,175.0,120.5,32.23,Monofásico Digital,Mora
MED-5738,Palestina,Comercial,360.0,122.0,81.48,Monofásico Digital,Mora
MED-5792,Villamaría,Comercial,175.0,128.0,58.12,Monofásico Digital,Mora
MED-5806,Villamaría,Comercial,290.5,120.5,52.04,Trifásico Industrial,Mora
MED-5822,Neira,Comercial,175.0,118.0,32.58,Monofásico Digital,Mora
MED-5833,Villamaría,Comercial,95.0,125.5,63.27,Monofásico Digital,Mora
MED-5850,Neira,Comercial,130.5,122.0,30.32,Monofásico Digital,Mora
MED-5864,Manizales,Comercial,175.0,122.0,68.23,Monofásico Digital,Mora
MED-5901,Palestina,Comercial,220.0,NaN,44.09,Monofásico Digital,Mora
MED-5937,Palestina,Comercial,220.0,118.0,81.29,Monofásico Digital,Mora
MED-5085,Manizales,Comercial,220.0,118.0,38.27,Monofásico Digital,Mora

In [21]:
#Punto 8: Construye una condición lógica con el operador & para encontrar lecturas donde el Tipo_Medidor comience con "B" (.str.startswith()) y las Horas_Pico_kWh sean mayores a 40.0.
filtro8=df_energia[(df_energia["Tipo_Medidor"].str.startswith("B")) & (df_energia["Horas_Pico_kWh"]>40.0)]
filtro8

,Municipio,Estrato,Consumo_kWh,Voltaje_Promedio,Horas_Pico_kWh,Tipo_Medidor,Estado_Pago
ID_Medidor,,,,,,,
MED-5006,Chinchiná,Estrato 4,175.0,120.5,50.49,Bifásico Inteligente,Financiado
MED-5008,Palestina,Estrato 1,220.0,120.5,51.93,Bifásico Inteligente,Mora
MED-5009,Villamaría,Estrato 2,130.5,122.0,45.63,Bifásico Inteligente,Mora
MED-5014,Neira,Estrato 4,290.5,112.5,69.74,Bifásico Inteligente,Al Día
MED-5018,Palestina,Estrato 2,NaN,120.5,54.42,Bifásico Inteligente,Mora
...,...,...,...,...,...,...,...
MED-5980,Villamaría,Comercial,95.0,120.5,73.78,Bifásico Inteligente,Al Día
MED-5983,Neira,Estrato 1,290.5,120.5,42.46,Bifásico Inteligente,Al Día
MED-5988,Palestina,Estrato 3,480.0,120.5,71.90,Bifásico Inteligente,Al Día
MED-5990,Villamaría,Estrato 2,220.0,118.0,44.74,Bifásico Inteligente,Al Día
MED-5992,Neira,Estrato 3,95.0,118.0,50.10,Bifásico Inteligente,Mora

In [27]:
#9: Tratamiento e Imputación de Nulos

filtro9=df_energia.fillna(
    {
        "Consumo_kWh": df_energia["Consumo_kWh"].mean(),
        "Voltaje_Promedio":120.0
    }
)
filtro9.loc["MED-5010"]

Municipio                          Neira
Estrato                        Estrato 3
Consumo_kWh                        130.5
Voltaje_Promedio                   120.0
Horas_Pico_kWh                     37.42
Tipo_Medidor        Bifásico Inteligente
Estado_Pago                       Al Día
Name: MED-5010, dtype: object

In [ ]:
#verificar nulos para poder comprobar el resultado en el punto 9 con una fila
cambios = df_energia[
    df_energia["Consumo_kWh"].isna() |
    df_energia["Voltaje_Promedio"].isna()
]

cambios

,Municipio,Estrato,Consumo_kWh,Voltaje_Promedio,Horas_Pico_kWh,Tipo_Medidor,Estado_Pago
ID_Medidor,,,,,,,
MED-5010,Neira,Estrato 3,130.5,NaN,37.42,Bifásico Inteligente,Al Día
MED-5018,Palestina,Estrato 2,NaN,120.5,54.42,Bifásico Inteligente,Mora
MED-5032,Neira,Estrato 2,NaN,112.5,69.90,Monofásico Digital,Mora
MED-5038,Villamaría,Estrato 2,175.0,NaN,75.11,Bifásico Inteligente,Al Día
MED-5072,Palestina,Estrato 2,175.0,NaN,52.99,Trifásico Industrial,Al Día
...,...,...,...,...,...,...,...
MED-5969,Chinchiná,Estrato 3,220.0,NaN,58.29,Bifásico Inteligente,Financiado
MED-5971,Neira,Estrato 2,NaN,120.5,60.01,Monofásico Digital,Financiado
MED-5978,Chinchiná,Estrato 3,NaN,125.5,69.36,Monofásico Digital,Al Día
MED-5995,Chinchiná,Estrato 3,130.5,NaN,75.91,Trifásico Industrial,Al Día
MED-6000,Palestina,Comercial,NaN,120.5,23.32,Monofásico Digital,Al Día

In [31]:
#Punto 10:Transformación Condicional con .apply()

def  nivel_taritario(n):

    if n<120.0:
        return "Bajo"
    elif n<= 250.0:
        return"Medio"
    else:
        return "Alto"



df_energia["Nivel_Consumo"]= df_energia["Consumo_kWh"].apply(nivel_taritario)
df_energia

,Municipio,Estrato,Consumo_kWh,Voltaje_Promedio,Horas_Pico_kWh,Tipo_Medidor,Estado_Pago,Nivel_Consumo
ID_Medidor,,,,,,,,
MED-5001,Villamaría,Estrato 3,130.5,118.0,32.74,Monofásico Digital,Al Día,Medio
MED-5002,Palestina,Estrato 2,175.0,120.5,19.97,Bifásico Inteligente,Al Día,Medio
MED-5003,Palestina,Estrato 1,220.0,118.0,11.71,Bifásico Inteligente,Mora,Medio
MED-5004,Neira,Estrato 4,130.5,128.0,64.26,Monofásico Digital,Al Día,Medio
MED-5005,Neira,Estrato 3,175.0,120.5,14.13,Monofásico Digital,Mora,Medio
...,...,...,...,...,...,...,...,...
MED-5088,Villamaría,Estrato 2,220.0,118.0,34.78,Trifásico Industrial,Al Día,Medio
MED-5089,Manizales,Estrato 3,220.0,122.0,62.85,Monofásico Digital,Al Día,Medio
MED-5090,Villamaría,Estrato 2,290.5,120.5,39.57,Bifásico Inteligente,Al Día,Alto
MED-5091,Palestina,Estrato 3,290.5,122.0,14.73,Trifásico Industrial,Al Día,Alto
MED-5092,Neira,Estrato 3,220.0,120.5,22.41,Trifásico Industrial,Financiado,Medio

In [36]:
#11.Renombrado y Reordenamiento de Columnas

df_energia.rename(
    columns={
        "Consumo_kWh": "Energia_kWh",
        "Tipo_Medidor": "Tecnologia"
    },inplace=True
)

cols = ["Nivel_Consumo"]

df_energia = df_energia[
    cols + [col for col in df_energia.columns if col not in cols]
]

df_energia

,Nivel_Consumo,Energia_kWh,Tecnologia,Municipio,Estrato,Voltaje_Promedio,Horas_Pico_kWh,Estado_Pago
ID_Medidor,,,,,,,,
MED-5001,Medio,130.5,Monofásico Digital,Villamaría,Estrato 3,118.0,32.74,Al Día
MED-5002,Medio,175.0,Bifásico Inteligente,Palestina,Estrato 2,120.5,19.97,Al Día
MED-5003,Medio,220.0,Bifásico Inteligente,Palestina,Estrato 1,118.0,11.71,Mora
MED-5004,Medio,130.5,Monofásico Digital,Neira,Estrato 4,128.0,64.26,Al Día
MED-5005,Medio,175.0,Monofásico Digital,Neira,Estrato 3,120.5,14.13,Mora
...,...,...,...,...,...,...,...,...
MED-5088,Medio,220.0,Trifásico Industrial,Villamaría,Estrato 2,118.0,34.78,Al Día
MED-5089,Medio,220.0,Monofásico Digital,Manizales,Estrato 3,122.0,62.85,Al Día
MED-5090,Alto,290.5,Bifásico Inteligente,Villamaría,Estrato 2,120.5,39.57,Al Día
MED-5091,Alto,290.5,Trifásico Industrial,Palestina,Estrato 3,122.0,14.73,Al Día
MED-5092,Medio,220.0,Trifásico Industrial,Neira,Estrato 3,120.5,22.41,Financiado

In [50]:
groupsbyCity = df_energia.groupby("Municipio")




agregate_data=groupsbyCity.agg(
{
    "Energia_kWh":"mean",
    "Horas_Pico_kWh":"sum"
}
)

agregate_data

            Energia_kWh  Horas_Pico_kWh
Municipio
Chinchiná    193.026882         8523.16
Manizales    200.181122         9109.86
Neira        192.365789         9217.37
Palestina    192.917910         9538.46
Villamaría   187.932292         8973.13

In [62]:
#11

def dispersion(series):
    return series.max()-series.min()


groupByEstrato=df_energia.groupby("Estrato").agg({
    "Energia_kWh":dispersion,
    "Voltaje_Promedio": dispersion

})
groupByEstrato

           Energia_kWh  Voltaje_Promedio
Estrato
Comercial        385.0              15.5
Estrato 1        385.0              15.5
Estrato 2        385.0              15.5
Estrato 3        385.0              15.5
Estrato 4        385.0              15.5

In [61]:


for estrato, grupo in df_energia.groupby("Estrato"):

    energia: pd.Series = grupo["Energia_kWh"]

    print(
        estrato,
        "min =", energia.min(),
        "max =", energia.max(),
        "range =", energia.max() - energia.min()
    )

Comercial min = 95.0 max = 480.0 range = 385.0
Estrato 1 min = 95.0 max = 480.0 range = 385.0
Estrato 2 min = 95.0 max = 480.0 range = 385.0
Estrato 3 min = 95.0 max = 480.0 range = 385.0
Estrato 4 min = 95.0 max = 480.0 range = 385.0

In [64]:
#12 Agrupamiento Multinivel:

groupMulti=df_energia.groupby(["Municipio","Estrato"])

groupMulti.agg(
    {
        "Energia_kWh":"mean",
        "Voltaje_Promedio":"mean"
    }
)

                      Energia_kWh  Voltaje_Promedio
Municipio  Estrato
Chinchiná  Comercial   188.115385        121.100000
           Estrato 1   184.027778        120.405405
           Estrato 2   205.702703        120.802632
           Estrato 3   196.818182        119.981132
           Estrato 4   185.968750        120.593750
Manizales  Comercial   183.017857        120.683333
           Estrato 1   222.088235        118.885714
           Estrato 2   186.532787        120.631148
           Estrato 3   219.377551        120.788462
           Estrato 4   184.666667        121.520833
Neira      Comercial   178.722222        120.433333
           Estrato 1   186.880000        119.705882
           Estrato 2   183.571429        120.121212
           Estrato 3   197.701923        120.265957
           Estrato 4   218.250000        119.958333
Palestina  Comercial   208.806452        119.967742
           Estrato 1   198.342105        121.153846
           Estrato 2   190.561404        120.245455
           Estrato 3   193.105769        120.632653
           Estrato 4   167.956522        121.704545
Villamaría Comercial   200.534483        120.900000
           Estrato 1   186.205882        120.114286
           Estrato 2   186.040984        120.653226
           Estrato 3   181.558140        120.025000
           Estrato 4   191.240000        119.565217

In [ ]:
#Viendo como se visualizan los datos para hacer la alternativa del punto 12
h=df_energia.groupby(["Municipio","Estrato"])
h.groups

{('Chinchiná',
  'Comercial'): Index(['MED-5061', 'MED-5066', 'MED-5073', 'MED-5074', 'MED-5096', 'MED-5130',
        'MED-5139', 'MED-5272', 'MED-5282', 'MED-5436', 'MED-5437', 'MED-5455',
        'MED-5501', 'MED-5508', 'MED-5512', 'MED-5515', 'MED-5595', 'MED-5644',
        'MED-5660', 'MED-5678', 'MED-5694', 'MED-5722', 'MED-5853', 'MED-5889',
        'MED-5891', 'MED-5921', 'MED-5972'],
       dtype='str', name='ID_Medidor'),
 ('Chinchiná',
  'Estrato 1'): Index(['MED-5043', 'MED-5053', 'MED-5076', 'MED-5121', 'MED-5125', 'MED-5233',
        'MED-5296', 'MED-5297', 'MED-5322', 'MED-5373', 'MED-5413', 'MED-5429',
        'MED-5447', 'MED-5469', 'MED-5475', 'MED-5482', 'MED-5488', 'MED-5499',
        'MED-5561', 'MED-5577', 'MED-5584', 'MED-5613', 'MED-5617', 'MED-5623',
        'MED-5629', 'MED-5655', 'MED-5657', 'MED-5666', 'MED-5741', 'MED-5782',
        'MED-5787', 'MED-5790', 'MED-5791', 'MED-5857', 'MED-5923', 'MED-5940',
        'MED-5952', 'MED-5960'],
       dtype='str', name='ID_Medidor'),
 ('Chinchiná',
  'Estrato 2'): Index(['MED-5058', 'MED-5110', 'MED-5128', 'MED-5150', 'MED-5152', 'MED-5247',
        'MED-5290', 'MED-5305', 'MED-5324', 'MED-5325', 'MED-5355', 'MED-5361',
        'MED-5385', 'MED-5394', 'MED-5440', 'MED-5442', 'MED-5452', 'MED-5459',
        'MED-5493', 'MED-5509', 'MED-5517', 'MED-5531', 'MED-5544', 'MED-5591',
        'MED-5632', 'MED-5651', 'MED-5698', 'MED-5713', 'MED-5749', 'MED-5751',
        'MED-5763', 'MED-5766', 'MED-5797', 'MED-5816', 'MED-5817', 'MED-5840',
        'MED-5868', 'MED-5883', 'MED-5956'],
       dtype='str', name='ID_Medidor'),
 ('Chinchiná',
  'Estrato 3'): Index(['MED-5015', 'MED-5016', 'MED-5023', 'MED-5028', 'MED-5055', 'MED-5122',
        'MED-5127', 'MED-5131', 'MED-5137', 'MED-5165', 'MED-5176', 'MED-5182',
        'MED-5188', 'MED-5220', 'MED-5228', 'MED-5241', 'MED-5271', 'MED-5303',
        'MED-5338', 'MED-5343', 'MED-5354', 'MED-5359', 'MED-5369', 'MED-5371',
        'MED-5382', 'MED-5414', 'MED-5421', 'MED-5428', 'MED-5467', 'MED-5496',
        'MED-5506', 'MED-5523', 'MED-5581', 'MED-5585', 'MED-5593', 'MED-5638',
        'MED-5723', 'MED-5734', 'MED-5785', 'MED-5786', 'MED-5803', 'MED-5807',
        'MED-5818', 'MED-5824', 'MED-5834', 'MED-5847', 'MED-5861', 'MED-5872',
        'MED-5890', 'MED-5905', 'MED-5908', 'MED-5936', 'MED-5969', 'MED-5978',
        'MED-5984', 'MED-5995'],
       dtype='str', name='ID_Medidor'),
 ('Chinchiná',
  'Estrato 4'): Index(['MED-5006', 'MED-5025', 'MED-5035', 'MED-5045', 'MED-5063', 'MED-5071',
        'MED-5100', 'MED-5135', 'MED-5198', 'MED-5255', 'MED-5261', 'MED-5265',
        'MED-5288', 'MED-5347', 'MED-5350', 'MED-5380', 'MED-5435', 'MED-5448',
        'MED-5453', 'MED-5514', 'MED-5521', 'MED-5576', 'MED-5647', 'MED-5658',
        'MED-5680', 'MED-5715', 'MED-5753', 'MED-5844', 'MED-5914', 'MED-5927',
        'MED-5928', 'MED-5962', 'MED-5987'],
       dtype='str', name='ID_Medidor'),
 ('Manizales',
  'Comercial'): Index(['MED-5011', 'MED-5085', 'MED-5109', 'MED-5142', 'MED-5148', 'MED-5159',
        'MED-5196', 'MED-5209', 'MED-5244', 'MED-5264', 'MED-5304', 'MED-5312',
        'MED-5329', 'MED-5349', 'MED-5358', 'MED-5360', 'MED-5415', 'MED-5468',
        'MED-5481', 'MED-5502', 'MED-5567', 'MED-5642', 'MED-5652', 'MED-5661',
        'MED-5737', 'MED-5781', 'MED-5808', 'MED-5864', 'MED-5907', 'MED-5085'],
       dtype='str', name='ID_Medidor'),
 ('Manizales',
  'Estrato 1'): Index(['MED-5022', 'MED-5030', 'MED-5048', 'MED-5104', 'MED-5146', 'MED-5166',
        'MED-5190', 'MED-5216', 'MED-5218', 'MED-5284', 'MED-5292', 'MED-5317',
        'MED-5326', 'MED-5377', 'MED-5430', 'MED-5444', 'MED-5538', 'MED-5558',
        'MED-5583', 'MED-5653', 'MED-5675', 'MED-5676', 'MED-5686', 'MED-5718',
        'MED-5794', 'MED-5813', 'MED-5820', 'MED-5849', 'MED-5852', 'MED-5854',
        'MED-5871', 'MED-5892', 'MED-5903', 'MED-5910', 'MED-5938', 'MED-5950'],
       dtype='str', name='ID_Medidor'),
 ('Manizales',
  'Estrato 2'): Index(['MED-5039', 'MED-5041', 'MED-5056', 'MED-5069', 'MED-5145', 'MED-5160',
        'MED-5163', 'MED-5184', 'MED-5219', 'MED-5222', 'MED-5231', 'MED-5245',
        'MED-5249', 'MED-5252', 'MED-5276', 'MED-5281', 'MED-5295', 'MED-5301',
        'MED-5306', 'MED-5323', 'MED-5333', 'MED-5370', 'MED-5378', 'MED-5402',
        'MED-5404', 'MED-5477', 'MED-5478', 'MED-5485', 'MED-5486', 'MED-5511',
        'MED-5518', 'MED-5533', 'MED-5586', 'MED-5590', 'MED-5645', 'MED-5649',
        'MED-5663', 'MED-5681', 'MED-5720', 'MED-5727', 'MED-5731', 'MED-5742',
        'MED-5744', 'MED-5757', 'MED-5769', 'MED-5775', 'MED-5776', 'MED-5784',
        'MED-5827', 'MED-5851', 'MED-5858', 'MED-5870', 'MED-5875', 'MED-5876',
        'MED-5882', 'MED-5893', 'MED-5897', 'MED-5902', 'MED-5904', 'MED-5917',
        'MED-5918', 'MED-5925', 'MED-5930', 'MED-5973'],
       dtype='str', name='ID_Medidor'),
 ('Manizales',
  'Estrato 3'): Index(['MED-5078', 'MED-5089', 'MED-5101', 'MED-5112', 'MED-5120', 'MED-5143',
        'MED-5175', 'MED-5197', 'MED-5205', 'MED-5212', 'MED-5237', 'MED-5253',
        'MED-5259', 'MED-5262', 'MED-5315', 'MED-5327', 'MED-5353', 'MED-5390',
        'MED-5400', 'MED-5403', 'MED-5425', 'MED-5464', 'MED-5472', 'MED-5474',
        'MED-5526', 'MED-5540', 'MED-5550', 'MED-5565', 'MED-5614', 'MED-5620',
        'MED-5621', 'MED-5626', 'MED-5643', 'MED-5648', 'MED-5687', 'MED-5700',
        'MED-5716', 'MED-5721', 'MED-5774', 'MED-5798', 'MED-5800', 'MED-5826',
        'MED-5856', 'MED-5874', 'MED-5877', 'MED-5886', 'MED-5933', 'MED-5935',
        'MED-5954', 'MED-5965', 'MED-5968', 'MED-5975', 'MED-5089'],
       dtype='str', name='ID_Medidor'),
 ('Manizales',
  'Estrato 4'): Index(['MED-5064', 'MED-5070', 'MED-5102', 'MED-5106', 'MED-5118', 'MED-5240',
        'MED-5313', 'MED-5319', 'MED-5356', 'MED-5386', 'MED-5457', 'MED-5471',
        'MED-5495', 'MED-5555', 'MED-5572', 'MED-5597', 'MED-5616', 'MED-5625',
        'MED-5682', 'MED-5697', 'MED-5788', 'MED-5831', 'MED-5862', 'MED-5866',
        'MED-5948', 'MED-5981'],
       dtype='str', name='ID_Medidor'),
 ('Neira',
  'Comercial'): Index(['MED-5013', 'MED-5021', 'MED-5027', 'MED-5052', 'MED-5081', 'MED-5095',
        'MED-5129', 'MED-5144', 'MED-5254', 'MED-5307', 'MED-5308', 'MED-5341',
        'MED-5479', 'MED-5527', 'MED-5535', 'MED-5562', 'MED-5582', 'MED-5667',
        'MED-5679', 'MED-5811', 'MED-5821', 'MED-5822', 'MED-5841', 'MED-5843',
        'MED-5850', 'MED-5881', 'MED-5885', 'MED-5926', 'MED-5944', 'MED-5949',
        'MED-5081'],
       dtype='str', name='ID_Medidor'),
 ('Neira',
  'Estrato 1'): Index(['MED-5029', 'MED-5033', 'MED-5034', 'MED-5050', 'MED-5119', 'MED-5133',
        'MED-5158', 'MED-5164', 'MED-5169', 'MED-5186', 'MED-5217', 'MED-5224',
        'MED-5243', 'MED-5258', 'MED-5266', 'MED-5268', 'MED-5274', 'MED-5283',
        'MED-5300', 'MED-5310', 'MED-5314', 'MED-5342', 'MED-5383', 'MED-5387',
        'MED-5393', 'MED-5405', 'MED-5407', 'MED-5422', 'MED-5450', 'MED-5494',
        'MED-5507', 'MED-5529', 'MED-5547', 'MED-5566', 'MED-5609', 'MED-5618',
        'MED-5685', 'MED-5690', 'MED-5692', 'MED-5714', 'MED-5729', 'MED-5739',
        'MED-5760', 'MED-5771', 'MED-5779', 'MED-5812', 'MED-5900', 'MED-5909',
        'MED-5955', 'MED-5982', 'MED-5983', 'MED-5993'],
       dtype='str', name='ID_Medidor'),
 ('Neira',
  'Estrato 2'): Index(['MED-5007', 'MED-5031', 'MED-5032', 'MED-5054', 'MED-5065', 'MED-5134',
        'MED-5136', 'MED-5151', 'MED-5161', 'MED-5167', 'MED-5238', 'MED-5246',
        'MED-5299', 'MED-5395', 'MED-5398', 'MED-5411', 'MED-5426', 'MED-5427',
        'MED-5498', 'MED-5536', 'MED-5541', 'MED-5548', 'MED-5553', 'MED-5571',
        'MED-5606', 'MED-5672', 'MED-5684', 'MED-5709', 'MED-5724', 'MED-5746',
        'MED-5756', 'MED-5795', 'MED-5810', 'MED-5835', 'MED-5860', 'MED-5939',
        'MED-5959', 'MED-5971'],
       dtype='str', name='ID_Medidor'),
 ('Neira',
  'Estrato 3'): Index(['MED-5005', 'MED-5010', 'MED-5024', 'MED-5077', 'MED-5080', 'MED-5092',
        'MED-5117', 'MED-5138', 'MED-5200', 'MED-5206', 'MED-5211', 'MED-5269',
        'MED-5328', 'MED-5330', 'MED-5344', 'MED-5352', 'MED-5364', 'MED-5375',
        'MED-5384', 'MED-5423', 'MED-5443', 'MED-5446', 'MED-5451', 'MED-5480',
        'MED-5510', 'MED-5545', 'MED-5552', 'MED-5560', 'MED-5605', 'MED-5608',
        'MED-5622', 'MED-5635', 'MED-5683', 'MED-5711', 'MED-5747', 'MED-5759',
        'MED-5762', 'MED-5783', 'MED-5802', 'MED-5832', 'MED-5837', 'MED-5845',
        'MED-5863', 'MED-5878', 'MED-5911', 'MED-5934', 'MED-5943', 'MED-5947',
        'MED-5958', 'MED-5992', 'MED-5999', 'MED-5092'],
       dtype='str', name='ID_Medidor'),
 ('Neira',
  'Estrato 4'): Index(['MED-5004', 'MED-5014', 'MED-5098', 'MED-5147', 'MED-5185', 'MED-5187',
        'MED-5202', 'MED-5225', 'MED-5270', 'MED-5275', 'MED-5309', 'MED-5334',
        'MED-5397', 'MED-5420', 'MED-5554', 'MED-5557', 'MED-5589', 'MED-5607',
        'MED-5650', 'MED-5677', 'MED-5688', 'MED-5719', 'MED-5764', 'MED-5768',
        'MED-5796', 'MED-5879', 'MED-5986'],
       dtype='str', name='ID_Medidor'),
 ('Palestina',
  'Comercial'): Index(['MED-5047', 'MED-5068', 'MED-5083', 'MED-5168', 'MED-5170', 'MED-5172',
        'MED-5183', 'MED-5204', 'MED-5214', 'MED-5226', 'MED-5236', 'MED-5277',
        'MED-5285', 'MED-5289', 'MED-5291', 'MED-5331', 'MED-5339', 'MED-5408',
        'MED-5497', 'MED-5528', 'MED-5568', 'MED-5570', 'MED-5627', 'MED-5630',
        'MED-5668', 'MED-5708', 'MED-5738', 'MED-5823', 'MED-5846', 'MED-5901',
        'MED-5929', 'MED-5937', 'MED-6000', 'MED-5083'],
       dtype='str', name='ID_Medidor'),
 ('Palestina',
  'Estrato 1'): Index(['MED-5003', 'MED-5008', 'MED-5017', 'MED-5057', 'MED-5086', 'MED-5099',
        'MED-5108', 'MED-5114', 'MED-5124', 'MED-5141', 'MED-5149', 'MED-5157',
        'MED-5199', 'MED-5201', 'MED-5287', 'MED-5320', 'MED-5336', 'MED-5376',
        'MED-5392', 'MED-5466', 'MED-5519', 'MED-5628', 'MED-5641', 'MED-5665',
        'MED-5671', 'MED-5693', 'MED-5733', 'MED-5740', 'MED-5765', 'MED-5767',
        'MED-5772', 'MED-5799', 'MED-5805', 'MED-5809', 'MED-5873', 'MED-5899',
        'MED-5912', 'MED-5932', 'MED-5977', 'MED-5991', 'MED-5998', 'MED-5086'],
       dtype='str', name='ID_Medidor'),
 ('Palestina',
  'Estrato 2'): Index(['MED-5002', 'MED-5018', 'MED-5026', 'MED-5036', 'MED-5062', 'MED-5072',
        'MED-5075', 'MED-5105', 'MED-5111', 'MED-5162', 'MED-5191', 'MED-5192',
        'MED-5230', 'MED-5235', 'MED-5273', 'MED-5311', 'MED-5351', 'MED-5406',
        'MED-5418', 'MED-5432', 'MED-5438', 'MED-5473', 'MED-5490', 'MED-5503',
        'MED-5505', 'MED-5516', 'MED-5524', 'MED-5532', 'MED-5534', 'MED-5546',
        'MED-5556', 'MED-5559', 'MED-5575', 'MED-5600', 'MED-5601', 'MED-5654',
        'MED-5664', 'MED-5689', 'MED-5701', 'MED-5702', 'MED-5703', 'MED-5730',
        'MED-5773', 'MED-5777', 'MED-5793', 'MED-5801', 'MED-5814', 'MED-5825',
        'MED-5836', 'MED-5838', 'MED-5839', 'MED-5855', 'MED-5906', 'MED-5924',
        'MED-5961', 'MED-5963', 'MED-5976', 'MED-5985'],
       dtype='str', name='ID_Medidor'),
 ('Palestina',
  'Estrato 3'): Index(['MED-5012', 'MED-5040', 'MED-5079', 'MED-5082', 'MED-5084', 'MED-5091',
        'MED-5097', 'MED-5115', 'MED-5173', 'MED-5194', 'MED-5215', 'MED-5223',
        'MED-5242', 'MED-5280', 'MED-5345', 'MED-5346', 'MED-5357', 'MED-5366',
        'MED-5374', 'MED-5379', 'MED-5396', 'MED-5399', 'MED-5433', 'MED-5454',
        'MED-5462', 'MED-5465', 'MED-5489', 'MED-5491', 'MED-5525', 'MED-5573',
        'MED-5574', 'MED-5578', 'MED-5631', 'MED-5639', 'MED-5646', 'MED-5659',
        'MED-5712', 'MED-5743', 'MED-5748', 'MED-5752', 'MED-5789', 'MED-5842',
        'MED-5848', 'MED-5865', 'MED-5941', 'MED-5946', 'MED-5964', 'MED-5966',
        'MED-5988', 'MED-5082', 'MED-5084', 'MED-5091'],
       dtype='str', name='ID_Medidor'),
 ('Palestina',
  'Estrato 4'): Index(['MED-5103', 'MED-5126', 'MED-5250', 'MED-5279', 'MED-5298', 'MED-5332',
        'MED-5401', 'MED-5409', 'MED-5412', 'MED-5416', 'MED-5424', 'MED-5439',
        'MED-5537', 'MED-5569', 'MED-5592', 'MED-5599', 'MED-5603', 'MED-5634',
        'MED-5699', 'MED-5706', 'MED-5707', 'MED-5732', 'MED-5919', 'MED-5989'],
       dtype='str', name='ID_Medidor'),
 ('Villamaría',
  'Comercial'): Index(['MED-5051', 'MED-5059', 'MED-5060', 'MED-5087', 'MED-5094', 'MED-5116',
        'MED-5155', 'MED-5156', 'MED-5193', 'MED-5239', 'MED-5256', 'MED-5263',
        'MED-5293', 'MED-5318', 'MED-5419', 'MED-5460', 'MED-5470', 'MED-5504',
        'MED-5587', 'MED-5611', 'MED-5615', 'MED-5717', 'MED-5792', 'MED-5806',
        'MED-5833', 'MED-5915', 'MED-5942', 'MED-5974', 'MED-5980', 'MED-5087'],
       dtype='str', name='ID_Medidor'),
 ('Villamaría',
  'Estrato 1'): Index(['MED-5093', 'MED-5181', 'MED-5207', 'MED-5208', 'MED-5221', 'MED-5229',
        'MED-5234', 'MED-5260', 'MED-5267', 'MED-5294', 'MED-5302', 'MED-5335',
        'MED-5417', 'MED-5434', 'MED-5456', 'MED-5483', 'MED-5484', 'MED-5513',
        'MED-5539', 'MED-5563', 'MED-5598', 'MED-5604', 'MED-5610', 'MED-5656',
        'MED-5691', 'MED-5696', 'MED-5705', 'MED-5736', 'MED-5745', 'MED-5750',
        'MED-5804', 'MED-5896', 'MED-5898', 'MED-5913', 'MED-5920', 'MED-5945',
        'MED-5951'],
       dtype='str', name='ID_Medidor'),
 ('Villamaría',
  'Estrato 2'): Index(['MED-5009', 'MED-5020', 'MED-5038', 'MED-5088', 'MED-5090', 'MED-5107',
        'MED-5113', 'MED-5154', 'MED-5174', 'MED-5178', 'MED-5179', 'MED-5180',
        'MED-5195', 'MED-5210', 'MED-5213', 'MED-5232', 'MED-5248', 'MED-5257',
        'MED-5321', 'MED-5337', 'MED-5348', 'MED-5362', 'MED-5368', 'MED-5381',
        'MED-5441', 'MED-5445', 'MED-5449', 'MED-5458', 'MED-5476', 'MED-5492',
        'MED-5542', 'MED-5549', 'MED-5551', 'MED-5579', 'MED-5580', 'MED-5594',
        'MED-5596', 'MED-5619', 'MED-5624', 'MED-5637', 'MED-5662', 'MED-5670',
        'MED-5695', 'MED-5710', 'MED-5725', 'MED-5726', 'MED-5754', 'MED-5761',
        'MED-5778', 'MED-5815', 'MED-5819', 'MED-5869', 'MED-5880', 'MED-5887',
        'MED-5895', 'MED-5922', 'MED-5967', 'MED-5970', 'MED-5979', 'MED-5990',
        'MED-5994', 'MED-5996', 'MED-5997', 'MED-5088', 'MED-5090'],
       dtype='str', name='ID_Medidor'),
 ('Villamaría',
  'Estrato 3'): Index(['MED-5001', 'MED-5019', 'MED-5037', 'MED-5042', 'MED-5044', 'MED-5046',
        'MED-5049', 'MED-5132', 'MED-5153', 'MED-5171', 'MED-5177', 'MED-5189',
        'MED-5227', 'MED-5251', 'MED-5286', 'MED-5340', 'MED-5363', 'MED-5388',
        'MED-5389', 'MED-5410', 'MED-5461', 'MED-5463', 'MED-5500', 'MED-5520',
        'MED-5522', 'MED-5530', 'MED-5588', 'MED-5602', 'MED-5612', 'MED-5633',
        'MED-5636', 'MED-5673', 'MED-5755', 'MED-5780', 'MED-5829', 'MED-5830',
        'MED-5859', 'MED-5867', 'MED-5888', 'MED-5894', 'MED-5916', 'MED-5931',
        'MED-5957'],
       dtype='str', name='ID_Medidor'),
 ('Villamaría',
  'Estrato 4'): Index(['MED-5067', 'MED-5123', 'MED-5140', 'MED-5203', 'MED-5278', 'MED-5316',
        'MED-5365', 'MED-5367', 'MED-5372', 'MED-5391', 'MED-5431', 'MED-5487',
        'MED-5543', 'MED-5564', 'MED-5640', 'MED-5669', 'MED-5674', 'MED-5704',
        'MED-5728', 'MED-5735', 'MED-5758', 'MED-5770', 'MED-5828', 'MED-5884',
        'MED-5953'],
       dtype='str', name='ID_Medidor')}

In [ ]:
#Otra forma forma de hacer el punto 12

for  dupla,datos in df_energia.groupby(["Municipio","Estrato"]):

    Municipio=dupla[0]
    estrato=dupla[1]

    Promedio_Energia_kWh= datos["Energia_kWh"].mean()
    Promedio_Voltaje_Promedio=datos["Voltaje_Promedio"].mean()

    

    print(
        (Municipio,estrato),
        "Promedio energia = " , Promedio_Energia_kWh,
        "Promedio Voltaje = " , Promedio_Voltaje_Promedio
        
    )

('Chinchiná', 'Comercial') Promedio energia =  188.1153846153846 Promedio Voltaje =  121.1
('Chinchiná', 'Estrato 1') Promedio energia =  184.02777777777777 Promedio Voltaje =  120.4054054054054
('Chinchiná', 'Estrato 2') Promedio energia =  205.7027027027027 Promedio Voltaje =  120.80263157894737
('Chinchiná', 'Estrato 3') Promedio energia =  196.8181818181818 Promedio Voltaje =  119.98113207547169
('Chinchiná', 'Estrato 4') Promedio energia =  185.96875 Promedio Voltaje =  120.59375
('Manizales', 'Comercial') Promedio energia =  183.01785714285714 Promedio Voltaje =  120.68333333333334
('Manizales', 'Estrato 1') Promedio energia =  222.08823529411765 Promedio Voltaje =  118.88571428571429
('Manizales', 'Estrato 2') Promedio energia =  186.5327868852459 Promedio Voltaje =  120.6311475409836
('Manizales', 'Estrato 3') Promedio energia =  219.37755102040816 Promedio Voltaje =  120.78846153846153
('Manizales', 'Estrato 4') Promedio energia =  184.66666666666666 Promedio Voltaje =  121.52083333333333
('Neira', 'Comercial') Promedio energia =  178.72222222222223 Promedio Voltaje =  120.43333333333334
('Neira', 'Estrato 1') Promedio energia =  186.88 Promedio Voltaje =  119.70588235294117
('Neira', 'Estrato 2') Promedio energia =  183.57142857142858 Promedio Voltaje =  120.12121212121212
('Neira', 'Estrato 3') Promedio energia =  197.70192307692307 Promedio Voltaje =  120.26595744680851
('Neira', 'Estrato 4') Promedio energia =  218.25 Promedio Voltaje =  119.95833333333333
('Palestina', 'Comercial') Promedio energia =  208.80645161290323 Promedio Voltaje =  119.96774193548387
('Palestina', 'Estrato 1') Promedio energia =  198.3421052631579 Promedio Voltaje =  121.15384615384616
('Palestina', 'Estrato 2') Promedio energia =  190.56140350877192 Promedio Voltaje =  120.24545454545455
('Palestina', 'Estrato 3') Promedio energia =  193.10576923076923 Promedio Voltaje =  120.63265306122449
('Palestina', 'Estrato 4') Promedio energia =  167.95652173913044 Promedio Voltaje =  121.70454545454545
('Villamaría', 'Comercial') Promedio energia =  200.5344827586207 Promedio Voltaje =  120.9
('Villamaría', 'Estrato 1') Promedio energia =  186.2058823529412 Promedio Voltaje =  120.11428571428571
('Villamaría', 'Estrato 2') Promedio energia =  186.04098360655738 Promedio Voltaje =  120.65322580645162
('Villamaría', 'Estrato 3') Promedio energia =  181.5581395348837 Promedio Voltaje =  120.025
('Villamaría', 'Estrato 4') Promedio energia =  191.24 Promedio Voltaje =  119.56521739130434